name: stellarplugin_example
description: Demonstrates how to use the stellarplugin plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  intl: ^0.16.1
  shared_preferences: ^0.5.6+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  stellarplugin:
    path: ../

flutter:

  uses-material-design: true
